### ISSUE TITLE
Create testing defaults/configuration

### ISSUE THREAD

**Issue by phaedryx** [danott/webpack_rails#10]
It would be nice if this also came with some recommendation for how to test the javascript. I currently use the konacha gem for running my javascript tests. With this I'm not sure how I would begin to write tests or how to run them. It would be nice if there were a generator that set up a basic test structure.

**Comment by danott** [comment]
This is an area worth exploring.

My gut reaction is that the use-cases for using Webpack as a build tool are so varied, that having a strong opinion about the best way to test may be hard to determine. Another concern is that the JavaScript community changes opinions quite frequently, and I don't necessarily want to sign us up for having to maintain in response to clockwork opinion changes.

**Comment by phaedryx** [comment]
Hmm, perhaps some documentation in the README that shows a way to do testing? It was the first question I had after getting things set up: "oh cool, this works with ES6 ... how do I test this code?"

**Comment by danott** [comment]
This remains a valid concern when setting up webpack. But without seeing any action to take at this moment, and considering the increasingly slow momentum on this project from myself, I'm going to close this issue for now.
