### ISSUE TITLE
Comparison to alternative ways of integrating WebPack

### ISSUE THREAD

**Issue by justin808** [danott/webpack_rails#12]
Hi Dan,

Can you please take a look at https://github.com/shakacode/react_on_rails/issues/22 and let us know if we should consider integrating our project into this (spec/dummy sample app) or into: https://github.com/shakacode/react-webpack-rails-tutorial. I wrote about this technique here: [Fast Rich Client Rails Development With Webpack and the ES6 Transpiler](http://www.railsonmaui.com/blog/2014/10/03/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/)

Right now, our webpack projects use for foreman and `webpack -w` to recompile the JavaScript.

Thanks.

**Comment by danott** [comment]
@justin808, I took a look at shakacode/react_on_rails#22, and I don't have any strong opinions, initially.

I don't think an open issue on this project is the appropriate place to discuss ideals for another project, so I am closing this issue.
